isomerpages/moe-teckwhyepri

_data/navigation.yml
=> Reopen Happenings Nav Menu

happenings/our-stories/_posts/2023-05-09-post-Appreciation to Our Preschool Teachers.md
=> Our Stories - Appreciation Preschool

_our-family/Our Staff.md
=> Updating Staff List for Term 3

_our-family/Our Staff.md
=> Update Eileen email address

_parents-hub/Service Providers.md
=> Update Dental Information

index.md
Remove Our Stories from Homepage
=> Remove Our Stories from Homepage

_parents-hub/Useful External Links.md
=> Update Useful External Links

_our-cca/Our Clubs & Societies.md
=> Update IMC description

_parents-hub/collection.yml
P1 Student Administration Reorder
=> P1 Student Administration Reorder

_parents-hub/Student Administrations/Application Forms & Booklist.md, _parents-hub/collection.yml
update the student administration
=> update the student administration

_our-family/Our Staff.md
Update Ong Huizhen Name in Our Staff
=> Update Huizhen Name in Our Staff

_our-family/Our Staff.md
=> Update Wai Mun email address

_about-us/School Advertisement/School Canteen Advertisement.md
School Canteen Advertisement (update)
=> School Canteen Advertisement (update)

_about-us/School Advertisement/School Canteen Advertisement.md
Canteen Advertisement (update)
=> Canteen Advertisement (update)

_parents-hub/Useful Information.md
Update After School Activity transport timing
=> Update After School Activity transport timing

_our-family/Our Staff.md
Remove Mages and Jothi from the List
=> Update Staff List

_parents-hub/Service Providers.md
=> School Dental Clinic Update

_our-family/Our Staff.md
Added 2 new SEN officer and updated the designation of the SEN Team
=> Update Our Staffs

_parents-hub/Service Providers.md
=> Updated Dental Clinic Details

_our-level-experiences/Primary 1.md, _our-level-experiences/Primary 2.md, _our-level-experiences/Primary 3.md, _our-level-experiences/Primary 4.md
=> Update on P1,P2,P3,P4

_our-family/Our Staff.md
Remove Karthik OM
Add Mr How
Add Mr Muthu
=> Update OM status under Staff

_our-family/Our Staff.md, _parents-hub/Service Providers/School Dental Clinic.md
=> Update Dental & Staff List

_about-us/Our Song.md, _our-family/Our Staff.md, _parents-hub/Service Providers/School Bookshop & Uniform.md, _parents-hub/Student Administrations/Forms & Booklists.md
Change Uniform Order form to online shop,
Staff List Update:
-Casey salutation change
- Nazri email change
- Wai Mun email change
- KP list order change
School Song Lyrics updated
=> Update Staff list, uniform order form, School Song

_parents-hub/Service Providers/School Bookshop & Uniform.md
=> Update Bookshop & Uniform

_parents-hub/Service Providers/School Bookshop & Uniform.md
=> Update Uniform 

_our-level-experiences/MOE Sexuality Education for P5 and P6 Students.md
=> Update Sexuality 2025

_parents-hub/Parents Portal.md
Parents engagement > corrected.
=> Parents Portal Update

_about-us/Our Song.md
remove youtube embedded Sch Song
=> Update Sch Song

_parents-hub/Service Providers/School Dental Clinic.md
=> update SDC schedule

_about-us/Our Achievements/2023 Achievements.md
=> Update Our Achievement 2023

_about-us/Our Achievements/2024 Achievements.md, _about-us/collection.yml, _our-family/Our Staff.md
Updated Staff List as of 14 Apr 2025
Updated Achievement 2024 and Eagles Awards Description.
=> Update Staff List & Achievement 2024

happenings/our-stories/_posts/2025-03-11-post-TWPS Achieved Three Stars in Green Schools @ South West 2024 and Platinum STAR for LOO Award 2024.md
=> update youtube video
